### ISSUE TITLE
Creating a person via the /person [post] method

### ISSUE THREAD

**Issue by phpology** [floatschedule/api#12] opened 2015-05-01 09:04 UTC
Hi Float team,

Hope you well.
I am trying to create a new person via the API but for some reason it does not like the job_title, email and skills parameter.
Below is the parameters I have used. 
name=Raj+Gorsia+14&job_title=Project+Manager&department=Project+Management&email=rgorsia%2Bfloat_pm14%40tsldigital.com&skills=PM

Is there like a list of allowed parameters that can be used. I assumed that majority would be allowed but of course I might be wrong.

thanks

Raj

**Comment by lgelfan** [comment] 2015-05-01 16:12
Hi Raj,

Thanks for using Float, sorry you are having problems. 

The department needs to be created separately for now so that value should only be department_id (we are looking into dynamic creation of linked data as a future enhancement). 

The other fields look correct. I will put in a request to update the documentation to make this more clear. 

--lars

**Comment by phpology** [comment] 2015-05-01 16:15
Hi Lars,

 

Thanks for your email.

 

Even if I take department out of the post, email and job_title don’t appear to save either. 

It just seems to like my name only and nothing else :|

 

Any suggestions please?

 

Thanks

 

Raj

**Comment by lgelfan** [comment] 2015-05-04 21:00
Hi Raj, when I use the exact raw query you provide, it works for me using the Advanced Rest Client. Make sure you have the request header: `Content-Type: application/x-www-form-urlencoded` set properly. Are you getting any error messages?

**Comment by lgelfan** [comment] 2016-01-20 03:39
Not reproducible with valid data, closing. Please let us know if you continue to have any problems.

**Closed by lgelfan** 2016-01-20 03:39 UTC
